### PR TITLE
Fixing links issue

### LINKED ISSUE #639: Remove search parameters on changing category
Currently on changing to a category via faceted search, the query parameters such as pagination stays on the URL.

### PR DESCRIPTION
**Pull request by acbeni**
fixes #639

### CODE REVIEW

File: product-catalog/app/com/commercetools/sunrise/productcatalog/productoverview/search/facetedsearch/categorytree/viewmodels/CategoryTreeFacetOptionViewModelFactory.java [hunk 1]
```diff
@@ -25,15 +25,24 @@
     private final List<Locale> locales;
     private final CategoryTree categoryTree;
     private final ProductReverseRouter productReverseRouter;
+    private final Set<String> ignoredParams;
```
Comment (lauraluiz) [inline product-catalog/app/com/commercetools/sunrise/productcatalog/productoverview/search/facetedsearch/categorytree/viewmodels/CategoryTreeFacetOptionViewModelFactory.java]: Why not make it static better and declare it directly in here?
```java
private static final Set<String> IGNORED_PARAMS = Collections.singleton("page"); 
```
It saves some lines of code and it's a bit more efficient.

File: common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java [hunk 2]
```diff
@@ -50,6 +48,20 @@ private QueryStringUtils() {
...
 
     /**
+     * Extracts the query string from the request.
+     * @param httpRequest current HTTP request
+     * @param ignoredParams params that should not be included in the link
+     * @return query string from the request
+     */
+    public static Map<String, List<String>> extractQueryString(final Http.Request httpRequest,final Set<String> ignoredParams) {
+
+        Set<String> ignored = Optional.ofNullable(ignoredParams).orElseGet(HashSet::new);
```
Comment (lauraluiz) [inline common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java]: In Sunrise we follow the rule that unless a parameter is annotated with `@Nullable`, it can't be null. Therefore this line of code is unnecessary.

File: common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java [hunk 3]
```diff
@@ -50,6 +48,20 @@ private QueryStringUtils() {
...
+        return httpRequest.queryString().entrySet().stream()
+                .filter(stringEntry -> !ignored.contains(stringEntry.getKey()))
+                .collect(toMap(Map.Entry::getKey, entry -> asList(entry.getValue())));
```
Comment (lauraluiz) [inline common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java]: To avoid duplication, I would let the other `extractQueryString` method to call this one with an empty set as `ignoredParams` (i.e. `Collections.emptySet()`). But I'm not sure how efficient would be the stream with a filter predicate that it's always false. Otherwise what we can surely avoid duplicating is the Collector `toMap(Map.Entry::getKey, entry -> asList(entry.getValue()))`. That would be enough to avoid duplication, I leave it to your decision :)

File: common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java [hunk 4]
```diff
@@ -50,6 +48,20 @@ private QueryStringUtils() {
     }
 
     /**
+     * Extracts the query string from the request.
+     * @param httpRequest current HTTP request
+     * @param ignoredParams params that should not be included in the link
+     * @return query string from the request
+     */
+    public static Map<String, List<String>> extractQueryString(final Http.Request httpRequest,final Set<String> ignoredParams) {
```
Comment (lauraluiz) [inline common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java]: We don't have many tests in Sunrise yet, but we actually have one for this class 😅 
Could you write some tests for this method?

File: product-catalog/app/com/commercetools/sunrise/productcatalog/productoverview/search/facetedsearch/categorytree/viewmodels/CategoryTreeFacetOptionViewModelFactory.java (hunk 1 above)
Comment (acbeni) [inline product-catalog/app/com/commercetools/sunrise/productcatalog/productoverview/search/facetedsearch/categorytree/viewmodels/CategoryTreeFacetOptionViewModelFactory.java]: 👍 good idea.
i will include t in the code review.

File: common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java (hunk 2 above)
Comment (acbeni) [inline common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java]: ok if thats the case it will keep the code cleaner 👍

File: common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java (hunk 4 above)
Comment (acbeni) [inline common/app/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtils.java]: 😅 didnt know we had a test for that one. 😄 now the test is added.

**Comment by acbeni** [comment]
@lauraluiz the code review has been done 👍

File: common/test/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtilsTest.java [hunk 5]
```diff
@@ -101,4 +102,17 @@ public void extractsQueryString() throws Exception {
...
                         .isEqualTo(queryString));
     }
+
+    @Test
+    public void extractsQueryStringIgnoringAParameter() throws Exception {
+
+        final String IGNORED_PARAM = "foo";
+        final Map<String, List<String>> queryString = someQueryString();
+
+        queryString.remove(IGNORED_PARAM);
```
Comment (lauraluiz) [inline common/test/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtilsTest.java]: If you remove the parameter it won't be there for the test and it will always pass ;)

Comment (acbeni) [inline common/test/com/commercetools/sunrise/framework/viewmodels/forms/QueryStringUtilsTest.java]: 👍 good catch
corrected.
