### PR TITLE
Fix payment not expanded error message, closes #502

### LINKED ISSUE #502: Fix payment not expanded error message
PaymentInfo is null when there's no payment yet. The error should be logged only when the references for the list of payments are not expanded.

``` java
final List<Reference<Payment>> paymentRefs = Optional.ofNullable(cart.getPaymentInfo())
        .map(PaymentInfo::getPayments)
        .orElseGet(() -> {
            logger.error("Payment info is not expanded in cart: the new payment information can be saved but the previous payments will not be removed.");
            return emptyList();
        });
```

### PR DESCRIPTION
**Pull request by lauraluiz**
Before it was logging the warning when paymentInfo was null (which happens when there are no payments yet) and now only when there are really not expanded. Also added a bit of documentation to let it clear.
I was thinking on fetching the payments if they are not expanded, but I'm afraid that will make people choose the easiest path, which affects a lot performance.

### CODE REVIEW

File: shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java [hunk 1]
```diff
@@ -102,4 +103,9 @@ private PaymentMethodInfo findPaymentMethod(final List<PaymentMethodInfo> paymen
                 .findAny()
                 .orElseThrow(() -> new RuntimeException("No valid payment method found")); // Should not happen after validation
     }
+
+    private boolean hasReferencesExpanded(final PaymentInfo paymentInfo) {
+        return paymentInfo.getPayments().stream()
+                .allMatch(reference -> reference.getObj() != null);
```
Comment (katmatt) [inline shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java]: Here it would be nice if our `Reference` class would provide a `isExpanded` method, this would then allow us to use a method handle here: `.allMatch(reference::isExpanded)`. 

WDYT?

File: shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java [hunk 2]
```diff
@@ -16,21 +17,23 @@
...
 import java.util.Optional;
 import java.util.concurrent.CompletionStage;
 
-import static java.util.Collections.emptyList;
 import static java.util.stream.Collectors.toList;
 
+/**
+ * Deletes previous payments associated with the cart and adds the new one.
+ * {@code paymentInfo.payments} must be expanded in order to properly work, otherwise previous payments will not be removed.
+ */
```
Comment (katmatt) [inline shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java]: Great that you wrote javadoc. I especially like how you describe the behavior 👍

File: shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java [hunk 3]
```diff
@@ -16,21 +17,23 @@
...
 import java.util.Objects;
 import java.util.Optional;
 import java.util.concurrent.CompletionStage;
 
-import static java.util.Collections.emptyList;
 import static java.util.stream.Collectors.toList;
 
+/**
+ * Deletes previous payments associated with the cart and adds the new one.
+ * {@code paymentInfo.payments} must be expanded in order to properly work, otherwise previous payments will not be removed.
```
Comment (katmatt) [inline shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java]: How about replacing '{@code...}' with `{@link PaymentInfo#getPayments()`? I prefer to use links because they add a bit more context. WDYT?

Comment (lauraluiz) [inline shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java]: Ah actually it was not a class, but the expansion path as it is expected by the platform :)
I will rewrite it to make it clear that I'm talking about paths.

File: shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java (hunk 1 above)
Comment (lauraluiz) [inline shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java]: Yes! I was actually thinking all the time "why don't we have a nice and useful method like that in the SDK??" 😄

File: shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java (hunk 3 above)
Comment (lauraluiz) [inline shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java]: In the end I joined both worlds :D

File: shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java (hunk 1 above)
Comment (lauraluiz) [inline shopping-cart/app/com/commercetools/sunrise/framework/checkout/payment/DefaultCheckoutPaymentControllerAction.java]: https://github.com/commercetools/commercetools-jvm-sdk/issues/1422
