### PR TITLE
Fix missing CSRF token, closes #522

### LINKED ISSUE #522: Unauthorized when adding to cart after following a link
When I open a browser tab for sunrise.commercetools.com and navigate to a pdp of a product, I can click the "Add to bag" button which will show the cart with that product added.

When I send a link to a product's pdp to someone else (or to myself and open it in another browser), clicking on "Add to bag" yields the following error:

```
Unauthorized
You must be authenticated to access this page.
```

We also encounter this issue in our project which is based on commercetools-sunrise-java.

I'm not sure whether this is related to #478.

### PR DESCRIPTION
**Pull request by lauraluiz**
@schleichardt please review. Besides fixing it, I made the PageMetaFactory as the others (https://github.com/commercetools/commercetools-sunrise-java/issues/416) taking the opportunity.

### CODE REVIEW

File: product-catalog/app/com/commercetools/sunrise/productcatalog/home/SunriseHomeController.java [hunk 1]
```diff
@@ -68,7 +64,8 @@ public Result index() {
 
     protected CompletionStage<Result> showHome() {
         return cmsPage().thenComposeAsync(cmsPage ->
-                asyncOk(renderPageWithTemplate(createPageContent(), getTemplateName(), cmsPage.orElse(null))));
+                        asyncOk(renderPageWithTemplate(createPageContent(), getTemplateName(), cmsPage.orElse(null))),
+                HttpExecution.defaultContext());
```
Comment (lauraluiz) [inline product-catalog/app/com/commercetools/sunrise/productcatalog/home/SunriseHomeController.java]: @schleichardt this little thing.
